#!/bin/bash

[ "$1" = --description ] && echo "ratelimit" && exit 0

[ "$1" = --linkinfo ] && echo "100mbps" && exit 0

PATH=$PATH:/sbin/:/usr/sbin

ETC=${ETC:-/etc}

ifname=""

[ "$1" = --interface ] && ifname=$2

