#!/bin/bash

[ "$1" = --description ] && echo "sfq" && exit 0

[ "$1" = --linkinfo ] && echo "1024/10" && exit 0

PATH=$PATH:/sbin/:/usr/sbin

ETC=${ETC:-/etc}

ifname=""

[ "$1" = --interface ] && ifname=$2
