#!/bin/bash

[ "$1" = --description ] && echo "Virtual" && exit 0

PATH=$PATH:/sbin/:/usr/sbin

ETC=${ETC:-/etc}
RCONF=${RCONF:-/usr/libexec/rconf}
OPT=${OPT:-/opt}

. $RCONF/librconf.sh

selections_basename rconf-interfaces-virtual 4
create_dialog_file
populate_dialog_file_desc

while true; do
    rc=$(dialog --stdout --backtitle "$ROUTER configuration" --title "Configure virtual interfaces" --ok-label Select --cancel-label Cancel --menu  "Choose type" 0 0 0 --file $F)

    [ $? = 0 ] || exit 0

    run_if_script "$rc"

done
