#!/bin/bash

[ "$1" = --description ] && echo "Per interface" && exit 0

RCONF=${RCONF:-/usr/libexec/rconf}
OPT=${OPT:-/opt}
ETC=${ETC:-/etc}

. $RCONF/librconf.sh

function confniclist {
    for f in $ETC/config.flags/*.nic; do
	[ ! -f "$f" ] && continue
	f=${f##*/}
	    . $ETC/config.data/$f
	    echo ${f/.nic/}
    done
}

function ifconf {
    local ifname=$1
    
    while true; do
	
	selections_linkinfo $ifname rconf-control-interface 4
        create_dialog_file
        populate_dialog_file_value

	rc=$(dialog --stdout --backtitle "$ROUTER configuration" --title "Configure traffic control for interface $ifname" --ok-label Select --cancel-label Cancel --default-item "$item" --menu  "Choose type of traffic control" 0 0 0 --file $F Save  "")

	[ $? = 0 ] || return 0

	item="$rc"

	run_if_script "$rc" --interface $ifname
    done
}

while true; do
    nics="$((ifinfo;confniclist)|sort|uniq)"
    
    create_dialog_file

    for nic in $nics; do
        echo \"$nic\" \"$(ifinfo -w -s - -i $nic driver)$(ifinfo -w -s Mbit- -i $nic speedmax)$(ifinfo -w -i $nic bus_info)\" >> $F
    done
    
    rc=$(dialog --stdout --backtitle "$ROUTER configuration" --title "Configure traffic control for interfaces" --ok-label Select --cancel-label Cancel --menu  "Choose interface" 0 0 0 --file $F)

    [ $? = 0 ] || exit 0
    
    ifconf $rc
done
